blueprint:
  name: Different_switches_zigbee2mqtt
  source_url: https://github.com/remb0/blueprints/tree/main/
  author: remb0
  description: >-
    <div>
      <h2>🔔 Switches!!</h2>
      <b>Version 0.9 Beta</b> | 🔗 <a href="https://github.com/remb0/blueprints/blob/main/Different_switches_zigbee2mqtt.yaml" target="_blank">Github Link</a> | 💬 <a href="https://community.home-assistant.io/t/zigbee2mqtt-2-0-different-switches-aqara-opple-ikea/" target="_blank">Community Topic</a>
      </div>
      <br>   
    Control anything you want with Opple or Aqara switches like WXCJKG13LM 
    event_types: single_left, single_right, single_both, double_left, double_right, double_both, hold_left, hold_right, hold_both 
    Ikea buttons: event_types: on, off, brightness_move_up, brightness_move_down, brightness_stop 
    
    * Each band button has single, double, triple, hold & release.. 
    
      Switch Button Layout (little dot lower left). Switch could be rotated like you want:     
      .---.---.---.     
      | 2 | 4 | 6 |
      |   |   |   |
      |.1 | 3 | 5 |
      '---'---'---'
    
    ***NOTE:*** Use zigbee2MQTT > 2025 

    ***Changelog:***
    added Aqara WXKG07LM for DAVIZINHO (Aqara_switches)  
  domain: automation
  homeassistant:
    min_version: 2024.12.0
  input:
    aqara_switch:
      name: switch
      description: Switch to use *
      selector:
        entity:
          domain:
          - event
          integration: mqtt
          multiple: false
    Ikea_sensor:
      name: Ikea sensor
      icon: mdi:cog
      collapsed: true
      input:
        aan:
          name: Ikea On button
          description: Action to after click on
          default: []
          selector:
            action: {}   
        uit:
          name: Ikea Off button
          description: Action to after click off
          default: []
          selector:
            action: {}
    single_switches:
      name: Single aqara rounded button
      icon: mdi:cog
      description: Aqara sensor to use
      collapsed: true      
      input:
        single:
          name: Single button
          description: Action to after click (ronde aqara buttons)
          default: []
          selector:
            action: {}            
    Aqara_switches:
      name: Aqara rocker and WXKG07LM switches
      collapsed: true          
      icon: mdi:cog
      input:
        single_left:
          name: Left button
          description: Action to run after single Left click
          default: []
          selector:
            action: {}      
        single_right:
          name: Right button
          description: Action to run after single right click
          default: []
          selector:
            action: {}
        hold_left:
          name: Left button
          description: Action to run after holding Right
          default: []
          selector:
            action: {} 
        hold_right:
          name: Right button
          description: Action to run after holding Right
          default: []
          selector:
            action: {}      
        hold_both:
          name: Hold both buttons
          description: Action to run after hold both buttons
          default: []
          selector:
            action: {}                                 
        single_both:
          name: single both buttons
          description: Action to run after single both click
          default: []
          selector:
            action: {}   
        double_left:
          name: double Left button
          description: Action to run after double left click
          default: []
          selector:
            action: {} 
        double_right:
          name: double Right button
          description: Action to run after double both click
          default: []
          selector:
            action: {}   
        double_both:
          name: double both buttons
          description: Action to run after single right click
          default: []
          selector:
            action: {}                                                                               
    Opple_switches:
      name: Opple switches
      collapsed: true        
      icon: mdi:buttons
      input:    
        button_1_single:
          name: Button 1 - Single Click
          description: Action to run after single click of button 1
          default: []
          selector:
            action: {}
        button_1_double:
          name: Button 1 - Double click
          description: Action to run after double click of button 1
          default: []
          selector:
            action: {}
        button_1_triple:
          name: Button 1 - Triple Click
          description: Action to run after triple click of button 1
          default: []
          selector:
            action: {}
        button_1_hold:
          name: Button 1 - Hold Down
          description: Action to run on holding down button 1
          default: []
          selector:
            action: {}
        button_1_release:
          name: Button 1 - Release after Hold
          description: Action to run after releasing button 1
          default: []
          selector:
            action: {}
        button_2_single:
          name: Button 2 - Single Click
          description: Action to run after single click of button 2
          default: []
          selector:
            action: {}
        button_2_double:
          name: Button 2 - Double click
          description: Action to run after double click of button 2
          default: []
          selector:
            action: {}
        button_2_triple:
          name: Button 2 - Triple Click
          description: Action to run after triple click of button 2
          default: []
          selector:
            action: {}
        button_2_hold:
          name: Button 2 - Hold Down
          description: Action to run on holding down button 2
          default: []
          selector:
            action: {}
        button_2_release:
          name: Button 2 - Release after Hold
          description: Action to run after releasing button 2
          default: []
          selector:
            action: {}
        button_3_single:
          name: Button 3 - Single Click
          description: Action to run after single click of button 3
          default: []
          selector:
            action: {}
        button_3_double:
          name: Button 3 - Double click
          description: Action to run after double click of button 3
          default: []
          selector:
            action: {}
        button_3_triple:
          name: Button 3 - Triple Click
          description: Action to run after triple click of button 3
          default: []
          selector:
            action: {}
        button_3_hold:
          name: Button 3 - Hold Down
          description: Action to run on holding down button 3
          default: []
          selector:
            action: {}
        button_3_release:
          name: Button 3 - Release after Hold
          description: Action to run after releasing button 3
          default: []
          selector:
            action: {}
        button_4_single:
          name: Button 4 - Single Click
          description: Action to run after single click of button 4
          default: []
          selector:
            action: {}
        button_4_double:
          name: Button 4 - Double click
          description: Action to run after double click of button 4
          default: []
          selector:
            action: {}
        button_4_triple:
          name: Button 4 - Triple Click
          description: Action to run after triple click of button 4
          default: []
          selector:
            action: {}
        button_4_hold:
          name: Button 4 - Hold Down
          description: Action to run on holding down button 4
          default: []
          selector:
            action: {}
        button_4_release:
          name: Button 4 - Release after Hold
          description: Action to run after releasing button 4
          default: []
          selector:
            action: {}
        button_5_single:
          name: Button 5 - Single Click
          description: Action to run after single click of button 5
          default: []
          selector:
            action: {}
        button_5_double:
          name: Button 5 - Double click
          description: Action to run after double click of button 5
          default: []
          selector:
            action: {}
        button_5_triple:
          name: Button 5 - Triple Click
          description: Action to run after triple click of button 5
          default: []
          selector:
            action: {}
        button_5_hold:
          name: Button 5 - Hold Down
          description: Action to run on holding down button 5
          default: []
          selector:
            action: {}
        button_5_release:
          name: Button 5 - Release after Hold
          description: Action to run after releasing button 5
          default: []
          selector:
            action: {}
        button_6_single:
          name: Button 6 - Single Click
          description: Action to run after single click of button 6
          default: []
          selector:
            action: {}
        button_6_double:
          name: Button 6 - Double click
          description: Action to run after double click of button 6
          default: []
          selector:
            action: {}
        button_6_triple:
          name: Button 6 - Triple Click
          description: Action to run after triple click of button 6
          default: []
          selector:
            action: {}
        button_6_hold:
          name: Button 6 - Hold Down
          description: Action to run on holding down button 6
          default: []
          selector:
            action: {}
        button_6_release:
          name: Button 6 - Release after Hold
          description: Action to run after releasing button 6
          default: []
          selector:
            action: {}
mode: parallel
max_exceeded: silent
trigger:
- platform: state
  entity_id: !input aqara_switch
condition:
  condition: template
  value_template: '{{ trigger.to_state.attributes.event_type in (
    ''on'',''off'',  
    ''single'',
    ''single_left'',''single_right'',''single_both'',''double_left'',''double_right'',''double_both'',''hold_left'',''hold_right'',''hold_both'',
    ''button_1_single'',
    ''button_1_double'', ''button_1_triple'', ''button_1_hold'', ''button_1_release'',
    ''button_2_single'', ''button_2_double'', ''button_2_triple'', ''button_2_hold'',
    ''button_2_release'', ''button_3_single'',''button_3_double'', ''button_3_triple'',
    ''button_3_hold'', ''button_3_release'', ''button_4_single'', ''button_4_double'',
    ''button_4_triple'', ''button_4_hold'', ''button_4_release'', ''button_5_single'',
    ''button_5_double'', ''button_5_triple'', ''button_5_hold'', ''button_5_release'',
    ''button_6_single'', ''button_6_double'', ''button_6_triple'', ''button_6_hold'',
    ''button_6_release'' ) }}'
action:
- variables:
    command: '{{ trigger.to_state.attributes.event_type }}'
- choose:
  - conditions:
    - '{{ command == ''on'' }}'
    sequence: !input aan
  - conditions:
    - '{{ command == ''off'' }}'  
    sequence: !input uit
  - conditions:
    - '{{ command == ''single'' }}'
    sequence: !input single
  - conditions:
    - '{{ command == ''single_left'' }}'
    sequence: !input single_left
  - conditions:
    - '{{ command == ''single_right'' }}'
    sequence: !input single_right
  - conditions:
    - '{{ command == ''single_both'' }}'
    sequence: !input single_both
  - conditions:
    - '{{ command == ''double_left'' }}'
    sequence: !input double_left
  - conditions:
    - '{{ command == ''double_right'' }}'
    sequence: !input double_right 
  - conditions:
    - '{{ command == ''double_both'' }}'
    sequence: !input double_both
  - conditions:
    - '{{ command == ''hold_left'' }}'
    sequence: !input hold_left
  - conditions:
    - '{{ command == ''hold_right'' }}'
    sequence: !input hold_right
  - conditions:
    - '{{ command == ''hold_both'' }}'
    sequence: !input hold_both                               
  - conditions:
    - '{{ command == ''button_1_single'' }}'
    sequence: !input button_1_single
  - conditions:
    - '{{ command == ''button_2_single'' }}'
    sequence: !input button_2_single
  - conditions:
    - '{{ command == ''button_3_single'' }}'
    sequence: !input button_3_single
  - conditions:
    - '{{ command == ''button_4_single'' }}'
    sequence: !input button_4_single
  - conditions:
    - '{{ command == ''button_5_single'' }}'
    sequence: !input button_5_single
  - conditions:
    - '{{ command == ''button_6_single'' }}'
    sequence: !input button_6_single
  - conditions:
    - '{{ command == ''button_1_double'' }}'
    sequence: !input button_1_double
  - conditions:
    - '{{ command == ''button_2_double'' }}'
    sequence: !input button_2_double
  - conditions:
    - '{{ command == ''button_3_double'' }}'
    sequence: !input button_3_double
  - conditions:
    - '{{ command == ''button_4_double'' }}'
    sequence: !input button_4_double
  - conditions:
    - '{{ command == ''button_5_double'' }}'
    sequence: !input button_5_double
  - conditions:
    - '{{ command == ''button_6_double'' }}'
    sequence: !input button_6_double
  - conditions:
    - '{{ command == ''button_1_triple'' }}'
    sequence: !input button_1_triple
  - conditions:
    - '{{ command == ''button_2_triple'' }}'
    sequence: !input button_2_triple
  - conditions:
    - '{{ command == ''button_3_triple'' }}'
    sequence: !input button_3_triple
  - conditions:
    - '{{ command == ''button_4_triple'' }}'
    sequence: !input button_4_triple
  - conditions:
    - '{{ command == ''button_5_triple'' }}'
    sequence: !input button_5_triple
  - conditions:
    - '{{ command == ''button_6_triple'' }}'
    sequence: !input button_6_triple
  - conditions:
    - '{{ command == ''button_1_hold'' }}'
    sequence: !input button_1_hold
  - conditions:
    - '{{ command == ''button_2_hold'' }}'
    sequence: !input button_2_hold
  - conditions:
    - '{{ command == ''button_3_hold'' }}'
    sequence: !input button_3_hold
  - conditions:
    - '{{ command == ''button_4_hold'' }}'
    sequence: !input button_4_hold
  - conditions:
    - '{{ command == ''button_5_hold'' }}'
    sequence: !input button_5_hold
  - conditions:
    - '{{ command == ''button_6_hold'' }}'
    sequence: !input button_6_hold
  - conditions:
    - '{{ command == ''button_1_release'' }}'
    sequence: !input button_1_release
  - conditions:
    - '{{ command == ''button_2_release'' }}'
    sequence: !input button_2_release
  - conditions:
    - '{{ command == ''button_3_release'' }}'
    sequence: !input button_3_release
  - conditions:
    - '{{ command == ''button_4_release'' }}'
    sequence: !input button_4_release
  - conditions:
    - '{{ command == ''button_5_release'' }}'
    sequence: !input button_5_release
  - conditions:
    - '{{ command == ''button_6_release'' }}'
    sequence: !input button_6_release